language: python

env:
    -
    - INSTALL_CONFIGOBJ=1

install:
    - pip install pyyaml
    - if [ "$INSTALL_CONFIGOBJ" -eq 1 ]; then pip install configobj; fi

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

script:
    - ./test.bash
