sudo: false

language: python

env:
    -
    - INSTALL_CONFIGOBJ=x
    - SYNTASTIC_EXTRAS_USE_CONFIG_PARSER=x

install:
    - pip install pyyaml
    - if [ -v INSTALL_CONFIGOBJ ]; then pip install configobj; fi

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

script:
    - ./test.bash
